Models/Categoria.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LanchesMac.Models;

[Table("Categorias")]
public class Categoria
{
    [Key]
    public int CategoriaId { get; set; }

    [Display(Name = "O nome da categoria")]
    [Required(ErrorMessage = "{0} deve ser informado.")]
    [MaxLength(100, ErrorMessage = "{0} deve ter no máximo {1} caracteres.")]
    public string Nome { get; set; }

    [Display(Name = "A descrição da categoria")]
    [Required(ErrorMessage = "{0} deve ser informada.")]
    [MaxLength(200, ErrorMessage = "{0} deve ter no máximo {1} caracteres.")]
    public string Descricao { get; set; }

    //Relacionamento Categoria-Lanche(s) (1 para muitos)
    public List<Lanche> Lanches { get; set; }
}

Models/ErrorViewModel.cs
namespace LanchesMac.Models;

public class ErrorViewModel
{
    public string RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Lanche.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LanchesMac.Models;

[Table("Lanches")]
public class Lanche
{
    [Key]
    public int LancheId { get; set; }

    [Display(Name = "O nome do lanche")]
    [Required(ErrorMessage = "{0} deve ser informado.")]
    [MinLength(10, ErrorMessage = "{0} deve ter no mínimo {1} caracteres.")]
    [MaxLength(80, ErrorMessage = "{0} ter no máximo {1} caracteres.")]
    public string Nome { get; set; }

    [Display(Name = "A descrição do lanche")]
    [Required(ErrorMessage = "{0} deve ser informada.")]
    [MinLength(20, ErrorMessage = "{0} deve ter no mínimo {1} caracteres.")]
    [MaxLength(100, ErrorMessage = "{0} ter no máximo {1} caracteres.")]
    public string DescricaoCurta { get; set; }

    [Display(Name = "A descrição detalhada do lanche")]
    [Required(ErrorMessage = "{0} deve ser informada.")]
    [MinLength(40, ErrorMessage = "{0} deve ter no mínimo {1} caracteres.")]
    [MaxLength(300, ErrorMessage = "{0} ter no máximo {1} caracteres.")]
    public string DescricaoDetalhada { get; set; }

    [Display(Name = "O preço do lanche")]
    [Required(ErrorMessage = "{0} deve ser informado.")]
    [Column(TypeName = "decimal(10,2)")]
    [Range(1, 999.99, ErrorMessage = "{0} deve estar entre {1} e {2}.")]
    public decimal Preco { get; set; }

    [Display(Name = "O caminho da imagem")]
    [MaxLength(200, ErrorMessage = "{0} deve ter no máximo {1} caracteres.")]
    public string ImagemUrl { get; set; }

    [Display(Name = "O caminho da miniatura")]
    [MaxLength(200, ErrorMessage = "{0} deve ter no máximo {1} caracteres.")]
    public string ImagemThumbnailUrl { get; set; }

    [Display(Name = "Lanche preferido?")]
    public bool IsLanchePreferido { get; set; }

    [Display(Name = "Lanche em estoque?")]
    public bool EmEstoque { get; set; }


    //Relacionamento Lanche-Categoria (1 para 1)
    public int CategoriaId { get; set; }
    public Categoria Categoria { get; set; }
}

ViewModels/LancheListViewModel.cs
using LanchesMac.Models;

namespace LanchesMac.ViewModels
{
    public class LancheListViewModel
    {
        public IEnumerable<Lanche> Lanches { get; set; }
        public string CategoriaAtual { get; set; }
    }
}

Controllers/HomeController.cs
using LanchesMac.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace LanchesMac.Controllers;

public class HomeController : Controller
{

    public IActionResult Index()
    {
        return View();
    }


    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/LancheController.cs
using LanchesMac.Models;
using LanchesMac.Repositories.Interfaces;
using LanchesMac.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace LanchesMac.Controllers
{
    public class LancheController : Controller
    {
        private readonly ILancheRepository _lancheRepository;

        public LancheController(ILancheRepository lancheRepository)
        {
            _lancheRepository = lancheRepository;
        }

        public IActionResult List()
        {
            //var lanches = _lancheRepository.Lanches;
            //return View(lanches);

            var viewModel = new LancheListViewModel();
            viewModel.Lanches = _lancheRepository.Lanches;
            viewModel.CategoriaAtual = "Categoria Atual";

            return View(viewModel);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

<h1> View Index </h1>

<partial name="_Carousel"></partial>

Views/Lanche/List.cshtml
@model LancheListViewModel

@{
    ViewData["Title"] = "Lanches";
}

<style>
    .card img {
        height: 30vh;
        width: 100%;
        border-radius: 10px;
        border: 1px solid lightgray;
                transition: 0.2s all;
    }

    .card {
        cursor: pointer;
        height: 100%;
    }

    .card:hover {
        box-shadow: rgba(149, 157, 165, 0.2) 0px 8px 24px;
    }

    .card:hover img {
        transform: scale(1.02);
    }
</style>

<div>
    <h2>@Model.CategoriaAtual</h2>

    <hr />

    <div class="container">
        <div class="row">
            @foreach (var lanche in Model.Lanches)
            {
                <partial name="_LanchesResumo" for="@lanche"></partial>
            }
        </div>
    </div>
</div>

Views/Shared/_Carousel.cshtml
<div id="carouselLanches" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="~/img/carousel_1.jpg" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="~/img/carousel_2.jpg" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="~/img/carousel_3.jpg" class="d-block w-100" alt="...">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselLanches" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselLanches" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

Views/Shared/_LanchesResumo.cshtml
@model Lanche

<div class="col-4 mb-3">
    <div class="card">
        <div class="card-body">
            <p><img src="~/img/lanches/@Model.ImagemUrl" class="img-fluid" /></p>
            <p>Preço: @Model.Preco.ToString("c")</p>
            <h4>Lanche: @Model.Nome</h4>
            <p>@Model.DescricaoCurta</p>
        </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LanchesMac</title>
    
    @* Libs *@
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

    @* Genérico *@
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LanchesMac.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LanchesMac</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Lanche" asp-action="List">Lanches</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - LanchesMac - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    
    @* Libs *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    @* Genérico *@
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>